# Generated by Django 5.1.1 on 2024-09-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=50)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app.batch')),
            ],
        ),
    ]
