# Generated by Django 5.1.1 on 2024-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lectures/pdfs/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
