# Generated by Django 5.1.1 on 2024-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lecture_pdf_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='pdf',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
